config/routes.rb
Evaluator::Application.routes.draw do
  resources :newtests
  match '/', :to => "evaluations#new"
  match '/evaluation-administration', :to => 'evaluations#evaluationadmin', :as => 'evaluationadmin'
  match '/evaluation-information', :to => 'evaluations#evaluationinfo', :as => 'evaluationinfo'
  match '/take-evaluation', :to => 'evaluations#takeevaluation', :as => 'takeevaluation'
  match '/evaluation-results', :to => 'evaluations#evaluationresults', :as => 'evaluationresults'
  match '/edit-evaluation', :to => 'evaluations#evaluationedit', :as => 'evaluationedit'
  match '/delete', :to => 'evaluations#delete', :as => 'delete'
  match '/questions', :to => 'evaluations#questions'
  match '/update-question', :to => 'evaluations#updatequestion', :as => 'updatequestion'
  match '/delete-question', :to => 'evaluations#deletequestion', :as => 'deletequestion'
  match '/question_results', :to => 'evaluations#question_results'
  match '/saveresults', :to => 'evaluations#saveresults', :as => 'saveresults'
  resources :evaluations
  

end

app/models/evaluation.rb
class Evaluation < ActiveRecord::Base
attr_accessible :name

  has_many :questions, :dependent => :destroy

  validates :name,  :presence => true,
    :length   => { :maximum => 50 },
    :uniqueness => true
end

app/models/newtest.rb
class Newtest < ActiveRecord::Base
end

app/models/question.rb
class Question < ActiveRecord::Base

attr_accessible :content

  belongs_to :evaluation

  has_many :question_results, :dependent => :destroy

  validates :content, :presence => true

  default_scope :order => 'questions.created_at ASC'
end

app/models/question_result.rb
class QuestionResult < ActiveRecord::Base
attr_accessible :answer

  belongs_to :question
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/evaluations_controller.rb
class EvaluationsController < ApplicationController
  def saveresults
    @evaluation = Evaluation.find(params[:id])
    @answersString = params[:answers].to_s
    @answers = params[:answers].to_s.split('x')
    @questions = @evaluation.questions
    @questions.each do |question|
      currentAnswer = @answers.shift
      currentAnswer = currentAnswer.to_i
      question.question_results.new(:Answer => currentAnswer).save
    end
    redirect_to evaluationresults_path(:id => params[:id])
  end

  def show
    @title = "Evaluations"
    @evaluation = Evaluation.find(0)
    @questions = @evaluation.questions
  end

  def questions
    @evaluation = Evaluation.find(params[:question][:evaluationid])
    @question = @evaluation.questions.new(params[:question]).save
    redirect_to  evaluationedit_path(:id => params[:question][:evaluationid])
  end

  def updatequestion
    Question.find(params[:questionid]).update_attributes(:content => params[:content])
    redirect_to  evaluationedit_path(:id => params[:id])
  end

  def deletequestion
    Question.delete(params[:questionid])
    redirect_to  evaluationedit_path(:id => params[:id])
  end

  def new
    @title = "Evaluations"
    @evaluation = Evaluation.new
    @evaluations = Evaluation.all
  end

  def create
    @title = "Evaluations"
    @evaluations = Evaluation.all
    @evaluation = Evaluation.new(params[:evaluation])
    @error = false
    if @evaluation.save
      redirect_to '/'
    else
      @error = true
      render 'new'
    end
  end

  def delete
    Evaluation.delete(params[:id])
    redirect_to '/'
  end

  def evaluationadmin
    @title = "Administration Page"
    @evaluation = Evaluation.find(params[:id])
  end

  def evaluationinfo
    @title = "Evaluation Information"
    @evaluation = Evaluation.find(params[:id])
  end

  def evaluationedit
    @title = "Edit Evaluation Questions"
    @evaluation = Evaluation.find(params[:id])
    @questions = @evaluation.questions
    @question = Question.new(params[:question])
  end

  def evaluationresults
    @title = "Evaluation Results"
    @evaluation = Evaluation.find(params[:id])
    @questions = @evaluation.questions
    @numQuestions = @questions.length
    @hasQuestions = false
    if(@numQuestions != 0)
      @hasQuestions = true
      @averageAnswers = Array.new(@numQuestions)
      @numberOfTimesAnswered = Array.new(@numQuestions)
      @total = 0
      @count = 0
      @hasResults = false
      if(@questions[0].question_results.length != 0)
        @hasResults = true
        @totalSubmissions = @questions[0].question_results.length
        @questions.each do |q|
          @total = 0
          q.question_results.each do |r|
            @total = @total + r.Answer.to_i
          end
          @averageAnswers[@count] = (@total.to_f/q.question_results.length.to_f).round * 135
          @numberOfTimesAnswered[@count] = q.question_results.length
          @count = @count + 1
        end
      end
    end
  end

  def takeevaluation
    @title = "Taking A Evaluation"
    @evaluation = Evaluation.find(params[:id])
    @questions = @evaluation.questions
    @question_result = "" 
  end

end

app/controllers/newtests_controller.rb
class NewtestsController < ApplicationController
  # GET /newtests
  # GET /newtests.json
  def index
    @newtests = Newtest.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @newtests }
    end
  end

  # GET /newtests/1
  # GET /newtests/1.json
  def show
    @newtest = Newtest.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @newtest }
    end
  end

  # GET /newtests/new
  # GET /newtests/new.json
  def new
    @newtest = Newtest.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @newtest }
    end
  end

  # GET /newtests/1/edit
  def edit
    @newtest = Newtest.find(params[:id])
  end

  # POST /newtests
  # POST /newtests.json
  def create
    @newtest = Newtest.new(params[:newtest])

    respond_to do |format|
      if @newtest.save
        format.html { redirect_to @newtest, notice: 'Newtest was successfully created.' }
        format.json { render json: @newtest, status: :created, location: @newtest }
      else
        format.html { render action: "new" }
        format.json { render json: @newtest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /newtests/1
  # PUT /newtests/1.json
  def update
    @newtest = Newtest.find(params[:id])

    respond_to do |format|
      if @newtest.update_attributes(params[:newtest])
        format.html { redirect_to @newtest, notice: 'Newtest was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @newtest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /newtests/1
  # DELETE /newtests/1.json
  def destroy
    @newtest = Newtest.find(params[:id])
    @newtest.destroy

    respond_to do |format|
      format.html { redirect_to newtests_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/question_results_controller.rb
class Question_ResultsController < ApplicationController

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/newtests_helper.rb
module NewtestsHelper
end

app/views/evaluations/evaluationadmin.html.erb
<p>Welcome Admin!!</p>
<div class="span-22 prepend-1 append-1">
  <h2>Personalize Your Evaluation: <%= @evaluation.name %></h2>
  <%= link_to "Edit Questions", evaluationedit_path(:id => @evaluation.id) %></br>
  <%= link_to "Create a new Evaluation", '/' %>
</div>
<div  class="span-22 prepend-1 append-1">
  <%= link_to "Destroy Evaluation", delete_path(:id => @evaluation.id), {:id => "hiddenYes"} %>
  <div class="span-7 mybutton-half myorange-hover" id="deleteEvaluationButton" onclick="verifySelection()">Delete this Evaluation</div>
  <div class="modificationWarning red questionnumber verificationWarning mygreen-hover" id="hiddenNo" onclick="hideVerification()">Keep Evaluation</div>
</div>
<div class="prepend-1 span-22 append-1">
  <div class="divider span-22">
  </div>
</div>
<div id="forward-backward-area" class="span-22 prepend-1 append-1">
  <%= link_to "Back", evaluationinfo_path(:id => @evaluation.id) %>
</div>

app/views/evaluations/evaluationedit.html.erb
<div class="span-22 prepend-1 append-1">
  <h2><%= @evaluation.name %></h2>
  <% counter = 0 %>
  <% @questions.each do |question| %>
    <div class="span-3 questionnumber">Question <%= (counter+1) %></div>
    <div class="span-19 last"><div class="modificationWarning red questionnumber" id="modified<%= counter %>">Has Not Been Updated</div></div>
    <div class="span-22 last"></div>
    <textarea class="span-16 submitQuestion" id="textArea<%= counter %>" number="<%= counter %>" ><%= question.content %></textArea>
    <div class="actions span-6 last">
      <%= link_to "Delete Question", deletequestion_path(:id => @evaluation.id, :questionid => question.id), {:class => 'span-5 submit-form-no-hover myred-hover'} %>
      <%= link_to "Update Question", updatequestion_path(:id => @evaluation.id, :questionid => question.id), {:class => 'span-5 submit-form-no-hover myblue-hover updateButton', :number => counter} %>
    </div>
    <div class="span-22 last"></div>
    <% counter = counter + 1 %>
  <% end %>
  <div class="span-7 questionnumber">Add Question <%= (counter+1) %></div>
  <div class="span-15 last"><div class="modificationWarning red questionnumber" id="modified<%= (counter) %>">Has Not Been Submitted</div></div>
  <div class="span-22 last" id="maxQuestion" number="<%= (counter+1) %>">
    <%= form_for(@question) do |f| %>
      <%= f.text_area :content, :class => "span-16 submitQuestion", :id => "textArea#{counter}", :number => "#{(counter)}" %>
      <div>
        <%= f.hidden_field :evaluationid, :value => "#{@evaluation.id}" %>
      </div>
      <div class="actions span-5 last">
        <%= f.submit "Add Question" %> 
      </div>
    <% end %>
  </div>
  <div class="divider span-22">
  </div>
</div>
<div id="forward-backward-area" class="span-22 prepend-1 append-1">
  <div class="span-4 mybutton-half myblack previousButtonSize" onclick="verifySelection()">Back</div> 
  <div class="span-4 mybutton-half myblack previousButtonSize" onclick="verifySelection2()">Home</div> 
</div>
<div  class="span-22 prepend-1 append-1">
  <%= link_to "Leave Page", evaluationadmin_path(:id => @evaluation.id), {:class => 'mygreen-hover modificationWarning red questionnumber verificationWarning', :id => "hiddenYes"} %>
  <div class="modificationWarning red questionnumber verificationWarning mygreen-hover" id="hiddenNo" onclick="hideVerification()">Stay Here</div>
</div>
<div  class="span-22 prepend-1 append-1">
  <%= link_to "Leave Page", '/', {:class => 'mygreen-hover modificationWarning red questionnumber verificationWarning', :id => "hiddenYes2"} %>
  <div class="modificationWarning red questionnumber verificationWarning mygreen-hover" id="hiddenNo2" onclick="hideVerification2()">Stay Here</div>
</div>

app/views/evaluations/evaluationinfo.html.erb
<div class="span-22 prepend-1 append-1 evaluation-information">
  <h2>Options For This Evaluation: <%= @evaluation.name %></h2>
  <%= link_to "Evaluate!", takeevaluation_path(:id => @evaluation.id) %><br/>
  <%= link_to "Current Evaluation Status", evaluationresults_path(:id => @evaluation.id) %><br/>
  <%= link_to "Create Questions", evaluationadmin_path(:id => @evaluation.id) %>
</div>
<div class="prepend-1 span-22 append-1">
  <div class="divider span-22">
  </div>
</div>
<div id="forward-backward-area" class="span-22 prepend-1 append-1">
  <%= link_to "back", '/' %>
</div>

app/views/evaluations/evaluationresults.html.erb
<div class="span-22 prepend-1 append-1">
  <h2>Evaluation: <%= @evaluation.name %></h2>
  <div class="span-22"></div>
  <% if(@hasQuestions == false) %>
    <h2>This evaluation has no questions</h2> 
  <% elsif(@hasResults == false) %>
    <h2>This evaluation has no submissions</h2> 
  <% else %>
    <h2>evaluation has <%= @totalSubmissions.to_s %> submissions. The average answers are below.</h2>
    <h2 class="resultRowText">Value 1 is least favorable and 5 is most favorable.</h2>
    <div class="span-22" style="margin-bottom: 10px;">
      <div class="resultLegend span-21">
        <div class="resultLegendVal">1</div>
        <div class="resultLegendVal">2</div>
        <div class="resultLegendVal">3</div>
        <div class="resultLegendVal">4</div>
        <div class="resultLegendVal">5</div>
      </div>
    </div>
    <% questionCount = 0 %>
    <div id="totalRows" value="<%= @numQuestions %>"></div>
    <% @averageAnswers.each do |val| %>
      <% questionCount = questionCount + 1 %>
      <div class="span-22 resultRow">
        <div class="span-22 last"><p class="resultRowText">Q<%= questionCount %>: <%= @questions[questionCount-1].content %></p></div>
        <div id="bar<%= questionCount %>" class="resultRowValue" style="background-color: #ffdd33;" value="<%= val.to_s %>">
          <p>Answered <%= @numberOfTimesAnswered[questionCount-1] %> Times</p>
        </div>
      </div>
    <% end %>
    <div class="span-22">
      <div class="resultLegend span-21">
        <div class="resultLegendVal">1</div>
        <div class="resultLegendVal">2</div>
        <div class="resultLegendVal">3</div>
        <div class="resultLegendVal">4</div>
        <div class="resultLegendVal">5</div>
      </div>
    </div>
  <% end %>
</div>
<div class="prepend-1 span-22 append-1">
  <div class="divider span-22">
  </div>
</div>
<div id="forward-backward-area" class="span-22 prepend-1 append-1">
  <%= link_to "Home", '/' %></br>
  <%= link_to "Home-Evaluation", evaluationinfo_path(:id => @evaluation.id) %>
</div>

app/views/evaluations/new.html.erb
<div class="span-22 prepend-1 append-1">
 <div class="divider span-22">
  </div>
<div align="justify">
  <div class="submitArea span-22">
<font face="ARIAL" size="4" color="#993600"><h2>CREATE NEW EVALUATION</h2></font>
<div class="span-22 prepend-1 append-1">  
 
  <%= form_for(@evaluation) do |f| %>
    <%= render 'shared/error_messages'%>
   
    <div class="field">
      <h3 class="submitLabel">Evaluation Name:</h3>
      <%= f.text_field :name, :class => "span-10 submitBox" %>
    
    </div>
    <div class="actions span-5 last">
      <%= f.submit "Create Evaluation", {:id => "submit-form", :class => "mygreen-hover"} %>
    </div>
  </div>
    </div>
  </div>
</div>

<font face="ARIAL" size="4" color="#993600"><h2>SELECT AMONG EXISTING EVALUATIONS</h2></font>
<div class="span-22 prepend-1 append-1">
  <div class="allEvaluationsArea span-22">
    <% counter = 0 %>
    <% @evaluations.each do |evaluation| %>
      <% if(counter == 0) %>
        <%= link_to evaluation.name, evaluationinfo_path(:id => evaluation.id) %></br>
      <% elsif(counter == 1) %>
        <%= link_to evaluation.name, evaluationinfo_path(:id => evaluation.id) %></br>
      <% else %>
        <%= link_to evaluation.name, evaluationinfo_path(:id => evaluation.id) %></br>
        <% counter = -1 %>
        <div class="span-22"></div>
      <% end %>
      <% counter = counter + 1 %>
    <% end %>
  </div>
</div>
</div>
<% end %>

app/views/evaluations/takeevaluation.html.erb
<div class="span-22 prepend-1 append-1">
  <h1><%= @evaluation.name %></h1>
  <h2>Points that you will give on the scale of 5</h2>
  <% counter = 0 %>
    <% @questions.each do |question| %>
      <div class="span-22 questionSpacer"><p><%= (counter+1) %><%=". " %><%= question.content %></p></div><br/>
      <div class="span-22 error-box hideError" id="errorset<%= counter %>">You cannot proceed without answering this question!</div>
      <div class="questionSpacer span-22"></div>
      <div class="span-22 radioButtonLabels">
        <div class="radioButtonLabel">1</div>
        <div class="radioButtonLabel">2</div>
        <div class="radioButtonLabel">3</div>
        <div class="radioButtonLabel">4</div>
        <div class="radioButtonLabel">5</div>
      </div>
      <div class="span-22 radiobuttons">
        <div class="radiobutton" selected="0" set="<%= counter %>" id="radioset<%= counter %>index1"></div>
        <div class="radiobutton" selected="0" set="<%= counter %>" id="radioset<%= counter %>index2"></div>
        <div class="radiobutton" selected="0" set="<%= counter %>" id="radioset<%= counter %>index3"></div>
        <div class="radiobutton" selected="0" set="<%= counter %>" id="radioset<%= counter %>index4"></div>
        <div class="radiobutton" selected="0" set="<%= counter %>" id="radioset<%= counter %>index5"></div>
      </div>
      <% counter = counter + 1 %>
    <% end %>
    <div id="numberOfQuestions" value="<%= counter %>"></div>
     
    <%= link_to "Submit Evaluation", saveresults_path(:id => @evaluation.id, :answers => "") %>
   
  
  
</div></br>
<div id="forward-backward-area" class="span-22 prepend-1 append-1">
  <div class="span-4 mybutton-half myblack previousButtonSize" onclick="verifySelection()">Back</div> 
  <div class="span-4 mybutton-half myblack previousButtonSize" onclick="verifySelection2()">Home</div> 
</div>
<div  class="span-22 prepend-1 append-1">
  <%= link_to "Leave Page", evaluationinfo_path(:id => @evaluation.id), {:class => 'mygreen-hover modificationWarning red questionnumber verificationWarning', :id => "hiddenYes"} %>
  <div class="modificationWarning red questionnumber verificationWarning mygreen-hover" id="hiddenNo" onclick="hideVerification()">Stay Here</div>
</div>
<div  class="span-22 prepend-1 append-1">
  <%= link_to "Leave Page", '/', {:class => 'mygreen-hover modificationWarning red questionnumber verificationWarning', :id => "hiddenYes2"} %>
  <div class="modificationWarning red questionnumber verificationWarning mygreen-hover" id="hiddenNo2" onclick="hideVerification2()">Stay Here</div>
</div>

app/views/layouts/_footer.html.erb
<div id="footer">
  <div id="copyright" class="span-24">
    <p>Copyright Rahul</p>
  </div>
</div>

app/views/layouts/_header.html.erb
<div id="header"> 
  <div class="span-22 prepend-1 append-1">
    <h1 id="<%= @title %>" >
      <%= @title %>
    </h1>
  </div>
</div>
<div id="below-header">
</div>
<div id="below-header2">
</div>

app/views/layouts/_stylesheets.html.erb
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SurveyEngine</title>
  <%= render "layouts/stylesheets" %>
  <%= stylesheet_link_tag :all %>
  <%= stylesheet_link_tag "survey" , :media => "all" %>
  <%= javascript_include_tag :defaults %>
  <%= javascript_include_tag "jquery-1.4.4.min" %>
  <%= javascript_include_tag "jquery-ui" %>
  <%= javascript_include_tag "editQuestionsPage" %>
  <%= javascript_include_tag "radioButtonHandler" %>
  <%= javascript_include_tag "verification" %>
  <%= javascript_include_tag "barchartGrowth" %>
  <%= csrf_meta_tag %>

</head>

<body class="<%= controller.controller_name %>">
  
    <div id="banner">
    <%= render "layouts/header", :locals => { :page_header => @page_header } %>
    </div>
    <div id="container">
    <div id="main-content">
      <%= yield %>
   </div>
</body>

</html>

app/views/newtests/_form.html.erb
<%= form_for(@newtest) do |f| %>
  <% if @newtest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@newtest.errors.count, "error") %> prohibited this newtest from being saved:</h2>

      <ul>
      <% @newtest.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/newtests/edit.html.erb
<h1>Editing newtest</h1>

<%= render 'form' %>

<%= link_to 'Show', @newtest %> |
<%= link_to 'Back', newtests_path %>

app/views/newtests/index.html.erb
<h1>Listing newtests</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @newtests.each do |newtest| %>
  <tr>
    <td><%= newtest.name %></td>
    <td><%= link_to 'Show', newtest %></td>
    <td><%= link_to 'Edit', edit_newtest_path(newtest) %></td>
    <td><%= link_to 'Destroy', newtest, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Newtest', new_newtest_path %>

app/views/newtests/new.html.erb
<h1>New newtest</h1>

<%= render 'form' %>

<%= link_to 'Back', newtests_path %>

app/views/newtests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @newtest.name %>
</p>


<%= link_to 'Edit', edit_newtest_path(@newtest) %> |
<%= link_to 'Back', newtests_path %>

app/views/shared/_error_messages.html.erb
<% if @evaluation.errors.any? %>
  <div id="error_explanation" >
    <% @evaluation.errors.full_messages.each do |msg| %>
        <div class="error-box myred-error error-field"><%= msg %></div>
    <% end %>
  </div>
  <div class="span-22"></div>
<% end %>